import type { Preset } from '../types';

export const PRESETS: Preset[] = [
  // Classic Turing
  {
    id: 'gs-spots',
    name: 'Mitosis',
    description: 'Self-replicating spots that divide like cells',
    category: 'Classic Turing',
    model: 'gray-scott',
    params: { F: 0.037, k: 0.06, Du: 0.21, Dv: 0.105, dt: 1.0 },
    initialCondition: 'center',
    colormap: 'viridis',
  },
  {
    id: 'gs-coral',
    name: 'Coral Growth',
    description: 'Branching coral-like structures',
    category: 'Classic Turing',
    model: 'gray-scott',
    params: { F: 0.062, k: 0.061, Du: 0.21, Dv: 0.105, dt: 1.0 },
    initialCondition: 'center',
    colormap: 'bioluminescent',
  },
  {
    id: 'gs-stripes',
    name: 'Stripes',
    description: 'Labyrinthine stripe patterns like fingerprints',
    category: 'Classic Turing',
    model: 'gray-scott',
    params: { F: 0.04, k: 0.06, Du: 0.21, Dv: 0.105, dt: 1.0 },
    initialCondition: 'noise',
    colormap: 'magma',
  },
  {
    id: 'snak-spots',
    name: 'Turing Spots',
    description: 'Classic Turing instability producing regular spots',
    category: 'Classic Turing',
    model: 'schnakenberg',
    params: { a: 0.1, b: 0.9, Du: 0.5, Dv: 0.1, dt: 0.01 },
    initialCondition: 'noise',
    colormap: 'plasma',
  },

  // Waves & Spirals
  {
    id: 'fhn-spirals',
    name: 'Spiral Waves',
    description: 'Rotating spiral wave patterns',
    category: 'Waves & Spirals',
    model: 'fitzhugh-nagumo',
    params: { a: 0.5, b: 0.8, epsilon: 0.01, Du: 0.2, Dv: 0.0, dt: 0.1 },
    initialCondition: 'center',
    colormap: 'twilight',
  },
  {
    id: 'fhn-target',
    name: 'Target Patterns',
    description: 'Concentric expanding rings',
    category: 'Waves & Spirals',
    model: 'fitzhugh-nagumo',
    params: { a: 0.3, b: 0.7, epsilon: 0.02, Du: 0.3, Dv: 0.0, dt: 0.1 },
    initialCondition: 'center',
    colormap: 'inferno',
  },
  {
    id: 'bruss-oscillate',
    name: 'Oscillations',
    description: 'Temporal oscillations with spatial structure',
    category: 'Waves & Spirals',
    model: 'brusselator',
    params: { a: 1.0, b: 3.0, Du: 0.5, Dv: 0.1, dt: 0.005 },
    initialCondition: 'noise',
    colormap: 'twilight',
  },

  // Exotic
  {
    id: 'gs-worms',
    name: 'Worms',
    description: 'Wriggling worm-like structures',
    category: 'Exotic',
    model: 'gray-scott',
    params: { F: 0.058, k: 0.065, Du: 0.21, Dv: 0.105, dt: 1.0 },
    initialCondition: 'noise',
    colormap: 'bioluminescent',
  },
  {
    id: 'gs-pulsing',
    name: 'Pulsing Dots',
    description: 'Spots that pulse and breathe rhythmically',
    category: 'Exotic',
    model: 'gray-scott',
    params: { F: 0.025, k: 0.06, Du: 0.21, Dv: 0.105, dt: 1.0 },
    initialCondition: 'symmetric',
    colormap: 'plasma',
  },
  {
    id: 'bruss-hex',
    name: 'Hexagonal Lattice',
    description: 'Regular hexagonal spot arrangement',
    category: 'Exotic',
    model: 'brusselator',
    params: { a: 1.5, b: 3.5, Du: 0.8, Dv: 0.15, dt: 0.005 },
    initialCondition: 'noise',
    colormap: 'magma',
  },

  // Artistic
  {
    id: 'gs-maze',
    name: 'Maze Runner',
    description: 'Dense labyrinthine corridors',
    category: 'Artistic',
    model: 'gray-scott',
    params: { F: 0.029, k: 0.057, Du: 0.21, Dv: 0.105, dt: 1.0 },
    initialCondition: 'noise',
    colormap: 'bone',
  },
  {
    id: 'gs-nebula',
    name: 'Nebula',
    description: 'Cloud-like diffuse patterns',
    category: 'Artistic',
    model: 'gray-scott',
    params: { F: 0.022, k: 0.051, Du: 0.21, Dv: 0.105, dt: 1.0 },
    initialCondition: 'noise',
    colormap: 'inferno',
  },
  {
    id: 'snak-stripes',
    name: 'Zebra',
    description: 'Clean black-and-white stripe bifurcation',
    category: 'Artistic',
    model: 'schnakenberg',
    params: { a: 0.05, b: 1.1, Du: 0.5, Dv: 0.05, dt: 0.01 },
    initialCondition: 'noise',
    colormap: 'grayscale',
  },
  {
    id: 'gs-mandala',
    name: 'Mandala',
    description: 'Symmetric radial pattern growth',
    category: 'Artistic',
    model: 'gray-scott',
    params: { F: 0.037, k: 0.06, Du: 0.21, Dv: 0.105, dt: 1.0 },
    initialCondition: 'symmetric',
    colormap: 'bioluminescent',
  },
];
